export const ROLES = {
  STUDENT: 'Student',
  SUPERVISOR: 'Supervisor',
  MODERATOR: 'Moderator',
  PAPERLEADER: 'PaperLeader',
  ADMIN: 'Admin',
  CLIENT: 'Client',
};

export const PERMISSIONS = {
  // Accessible to all
  CREATE_ISSUE: 'create:issue',
  VIEW_MY_ISSUE: 'view:ownIssue',

  // Admin permissions
  APPROVE_USER: 'approve:user',

  // PaperLeader permissions
  VIEW_ALL_ISSUE: 'view:allIssue',
  VIEW_PROJECT: 'view:project',
  CREATE_PROJECT: 'create:project',
  VIEW_ISSUETYPE: 'view:issueType',
  CREATE_ISSUETYPE: 'create:issueType',
};

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  [ROLES.STUDENT]: [PERMISSIONS.CREATE_ISSUE, PERMISSIONS.VIEW_MY_ISSUE],
  [ROLES.SUPERVISOR]: [PERMISSIONS.CREATE_ISSUE, PERMISSIONS.VIEW_MY_ISSUE],
  [ROLES.MODERATOR]: [PERMISSIONS.CREATE_ISSUE, PERMISSIONS.VIEW_MY_ISSUE],
  [ROLES.PAPERLEADER]: [
    PERMISSIONS.CREATE_ISSUE,
    PERMISSIONS.VIEW_MY_ISSUE,
    PERMISSIONS.VIEW_ALL_ISSUE,
    PERMISSIONS.VIEW_PROJECT,
    PERMISSIONS.CREATE_PROJECT,
    PERMISSIONS.VIEW_ISSUETYPE,
    PERMISSIONS.CREATE_ISSUETYPE,
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.CREATE_ISSUE,
    PERMISSIONS.VIEW_MY_ISSUE,
    PERMISSIONS.APPROVE_USER,
  ],
  [ROLES.CLIENT]: [PERMISSIONS.CREATE_ISSUE, PERMISSIONS.VIEW_MY_ISSUE],
};
